version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: sitetest_local_django
    container_name: sitetest_django
    depends_on:
      - postgres
    volumes:
      # - .:/app:z
      - .:/workspace:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sitetest_production_postgres
    container_name: sitetest_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "8080:5432"

  docs:
    image: sitetest_local_docs
    container_name: sitetest_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/workspace/config:z
      - ./sitetest:/workspace/sitetest:z
    ports:
      - "7000:7000"
    command: /start-docs

  redis:
    image: redis:5.0
    container_name: sitetest_redis

  celeryworker:
    <<: *django
    image: sitetest_local_celeryworker
    container_name: sitetest_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: sitetest_local_celerybeat
    container_name: sitetest_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: sitetest_local_flower
    container_name: sitetest_flower
    ports:
      - "5555:5555"
    command: /start-flower
