# Generated by Django 3.0.11 on 2021-03-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
